### ISSUE TITLE
Missing gpgme, package has been renamed

### ISSUE THREAD

**Issue by danielschonfeld** [orhun/gpg-tui#10]
**Describe the bug**

Missing gpgme

**Additional context**

I believe in modern distributions, the package has been renamed to python-gpg and with it the executable file.  It's no longer called gpgme.  Perhaps the requirements listed are old?

**Comment by ptaranat** [comment]
On Debian, this can be solved by installing libgpgme-dev from a package manager.

**Comment by perplexa** [comment]
When running `cargo install gpg-tui` on MacOS, it also fails with a gpgme related error:
```
  sh: gpgme-config: command not found
```

**Comment by orhun** [comment]
> I believe in modern distributions, the package has been renamed to python-gpg and with it the executable file. It's no longer called gpgme. Perhaps the requirements listed are old?

Good point. I actually mentioned "gpgme" as "gpgme" in the documentation because the name of the "gpgme" package might change depending on the distribution. But apparently I forgot to mention this.

**Comment by orhun** [comment]
> When running `cargo install gpg-tui` on MacOS, it also fails with a gpgme related error:
> 
> ```
>   sh: gpgme-config: command not found
> ```

It mostly happens when development files for `gpgme` is not installed. See [gpgme#building](https://github.com/gpg-rs/gpgme#building).

Unfortunately there's not much I can do about it since [build.rs](https://github.com/gpg-rs/gpgme/blob/master/gpgme-sys/build.rs) is ran during `cargo install`. Also I don't have the opportunity to test/reproduce it on MacOS.

Feel free to open a separate issue for tracking/solving the `gpgme`-build related problems.
